Odagada/Trimo-FE

pages/_document.tsx
=> fix: import NextScript

.eslintrc.json, .husky/pre-commit, .husky/pre-push, .prettierrc.json, .storybook/main.ts, next.config.js, package-lock.json, package.json, postcss.config.js, styles/globals.css, tailwind.config.ts
=> [Chore] husky를 통한 prettier와 eslint 자동 처리

.eslintrc.json, .github/ISSUE_TEMPLATE/feature.yml, .husky/pre-commit, .husky/pre-push, .prettierrc.json, .storybook/main.ts, next.config.js, package-lock.json, package.json, postcss.config.js, styles/globals.css, tailwind.config.ts
Issue에도 체크박스 만들었습니다!
- 단순한 이슈 템플릿 수정한 코드라 어푸 받으면 바로 메인에 머지 하겠습니다!
- 아직 진호님 허스키 설정밖에 추가로 develop에 코드 적용된거 없어서 일단 여기까지 메인에 머지해도 될 듯 합니다
=> Issue Template 수정

styles/globals.css
=> [Fix] globalcss 배경색 오류 수정

styles/globals.css
=> Revert "[Fix] globalcss 배경색 오류 수정"

styles/globals.css
- 메인에다가 머지해서 다시 revert하고 디벨롭에 다시 머지합니다.....ㅠ
=> [Fix] Global CSS 디폴트 코드 삭제

apis/axios.ts, business/updateToken.ts
=> [feat] axios instance 등 기본 구성

.gitignore
=> [Feat] Test Page 추가

.eslintrc.json
=> [Chore] Eslint rules 추가

apis/capsulesQuery.ts, components/atoms/ImagesCarousel.tsx, types/client.types.ts, types/server.types.ts
- 타입 쪽 변경된 거 봐주시고 수정할 타입 있으시면 말씀해주세요
=> [Refactor] types 수정

components/atoms/SearchOption.tsx, components/atoms/TimePicker.tsx, components/molecules/SearchFrom.tsx, components/molecules/TagRadioButton.tsx, package-lock.json, package.json, stories/assets/TimePicker.stories.tsx
- search form 제작
- time picker랑 겹치는 부분이 있어서 #60  머지하지 않고 그냥 close하겠습니다
- `  function handleSearch(data: query) {}` 여기에 서브밋하는 함수 넣으시면 됩니다
=> [Feat] search form

types/client.types.ts, types/server.types.ts
=> [hotfix] 타입 추가 및 client의 review 타입 수정

apis/capsulesQuery.ts, components/atoms/Inputs/SearchBar.tsx, components/molecules/MultiReviewCardSlider.tsx, components/organisms/GoogleMap.tsx, pages/index.tsx, pages/review/[id].tsx
=> [Refactor] 메인 페이지 리팩토링

package-lock.json, package.json, utils/makeToast.ts
=> [Feat] Toast 구현

utils/calcDate.ts
- response 변경에 따른 calcDate 함수 변경
=> [Fix] calcDate함수 변경

appspec.yml, deploy.sh
=> chore: aws테스트

deploy.sh
=> chore: deploy.sh 변경

deploy.sh
=> chore : deploy 변경

components/atoms/DatePicker.tsx, components/atoms/TimePicker.tsx, utils/formatHours.ts, utils/formatTime.ts
- formatHours, DateTime 함수 로직 병합
- 하나로 합쳤습니다
=> [refactor] format 함수 로직 병합

apis/reviewPost.ts, components/molecules/ReviewWrite.tsx
- apiKey 연결
- cookie에서 apiKey받아다가 넘겼습니다
=> [refactor] apiKey 연결

pages/login/index.tsx
=> [refactor]: Social Login Redirect Uri 이전

pages/_document.tsx
=> [Chore] document 원상복귀

components/atoms/ReviewCardTag.tsx, components/atoms/SingleStarRate.tsx, components/molecules/ReviewCard.tsx, tailwind.config.ts
=> [Refactor] review card 반응형

components/molecules/NavigationBar.tsx
=> [Feat] NavBar 반응형 구현

apis/capsulesQuery.ts, components/molecules/NoResult.tsx, components/molecules/ReviewCard.tsx, components/molecules/ReviewList.tsx, components/organisms/SearchContent.tsx, styles/globals.css
=> [refactor] 리뷰 리스트 반응형 추가

apis/axios.ts
=> [hofix] server domain 변경

apis/axios.ts, hooks/signup/useGetUserSocialInfo.tsx, hooks/signup/useValidateNickname.tsx, pages/signup/[provider].tsx
=> [hofix] domain 수정

next.config.js
=> [hotfix] config domain 수정

next.config.js
=> Revert "[hotfix] config domain 수정"

README.md, apis/axios.ts, next.config.js
=> Revert "Readme"

pages/review/[id].tsx
=> refactor : fatcher에서 fetch 함수로 변경해봄

components/molecules/ReviewEdit.tsx, components/molecules/ReviewList.tsx, utils/makeToast.ts
- useState setValue 해제
- 테스트입니다
=> [Fix] review edit

components/atoms/Inputs/ImagesInput.tsx
- review imginput scroll hidden
- 리뷰 이미지 인풋에 스크롤 없앴습니다
=> [Fix] : review scroll hidden

components/atoms/Footer.tsx
- 개인정보 처리방침 노션 작성 및 링크 연결
- 푸터만 링크걸었습니다
=> fix: footer 개인정보 처리방침 링크

pages/review/[id]/index.tsx
=> [Style] review 제목 부분 스타일 수정

pages/index.tsx, pages/review/index.tsx
=> test : aws ci/cd 테스트

components/atoms/ImagesCarousel.tsx, pages/review/[id]/index.tsx
=> feat : 이미지 처리 추가

apis/capsulesQuery.ts, components/molecules/ReviewCard.tsx, components/organisms/SearchContent.tsx, hooks/useIntersectionObserver.tsx, pages/search/index.tsx, types/server.types.ts
=> [feat] 무한 스크롤

apis/axios.ts
=> [chore] api 주소 변경
